### ISSUE TITLE
не запускается майн с модом

### ISSUE THREAD

**Issue by JiMoon69** [sxmurxy2005/TopkaHitboxes-2.0#1]
ассалам алейкум (я знаю что автор русский)

не запускается майн с топка-хитбоксес

лог:
`[23июн2023 00:57:23.980] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmluserdevclient, --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, --fml.forgeVersion, 36.2.34, --assetIndex, 1.16, --assetsDir, /Users/yt/.gradle/caches/forge_gradle/assets, --version, MOD_DEV, --username, Dev, --accessToken, ❄❄❄❄❄❄❄❄, --userProperties, {}]
[23июн2023 00:57:23.986] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 8.1.3+8.1.3+main-8.1.x.c94d18ec starting: java version 1.8.0_372 by Temurin
[23июн2023 00:57:24.338] [main/INFO] [net.minecraftforge.fml.loading.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[23июн2023 00:57:24.400] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/Users/yt/.gradle/caches/modules-2/files-2.1/org.spongepowered/mixin/0.8.4/4ec7d77d9ab32596ca0b78bb123956734767e3a/mixin-0.8.4.jar Service=ModLauncher Env=CLIENT
[23июн2023 00:57:26.920] [main/ERROR] [mixin/]: Mixin config topkahitboxes.mixin.json does not specify "minVersion" property
[23июн2023 00:57:26.924] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmluserdevclient' with arguments [--version, MOD_DEV, --gameDir, ., --assetsDir, /Users/yt/.gradle/caches/forge_gradle/assets, --assetIndex, 1.16, --username, Dev, --accessToken, ❄❄❄❄❄❄❄❄, --userProperties, {}]
[23июн2023 00:57:37.050] [Render thread/INFO] [com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService/]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[23июн2023 00:57:39.092] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Setting user: Dev
[23июн2023 00:57:39.222] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Backend library: LWJGL version 3.2.1 build 12
[23июн2023 00:57:40.044] [modloading-worker-0/INFO] [net.minecraftforge.common.ForgeMod/FORGEMOD]: Forge mod loading, version 36.2.34, for MC 1.16.5 with MCP 20210115.111550
[23июн2023 00:57:40.047] [modloading-worker-0/INFO] [net.minecraftforge.common.MinecraftForge/FORGE]: MinecraftForge v36.2.34 Initialized
[23июн2023 00:57:40.083] [modloading-worker-3/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: topkahitboxes, class dev.sxmurxy.topkahitboxes.TopkaHitboxes
java.lang.NoSuchFieldError: field_151161_ac
	at dev.sxmurxy.topkahitboxes.TopkaHitboxes$Settings.<init>(TopkaHitboxes.java:67) ~[topkahitboxes:2.0-1.16.5-forge]
	at dev.sxmurxy.topkahitboxes.TopkaHitboxes.<init>(TopkaHitboxes.java:36) ~[topkahitboxes:2.0-1.16.5-forge]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_372]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_372]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_372]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_372]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_372]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[forge:36.2]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) [?:1.8.0_372]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632) [?:1.8.0_372]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_372]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_372]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_372]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) [?:1.8.0_372]
[23июн2023 00:57:40.119] [modloading-worker-1/INFO] [STDERR/]: [ru.saintby.SaintByClient.helpers.font.CustomFont:<init>:44]: java.io.IOException: Problem reading font data.
[23июн2023 00:57:40.119] [modloading-worker-1/INFO] [STDERR/]: [ru.saintby.SaintByClient.helpers.font.CustomFont:<init>:44]: 	at java.awt.Font.createFont0(Font.java:1000)
[23июн2023 00:57:40.119] [modloading-worker-1/INFO] [STDERR/]: [ru.saintby.SaintByClient.helpers.font.CustomFont:<init>:44]: 	at java.awt.Font.createFont(Font.java:877)
[23июн2023 00:57:40.120] [modloading-worker-1/INFO] [STDERR/]: [ru.saintby.SaintByClient.helpers.font.CustomFont:<init>:44]: 	at ru.saintby.SaintByClient.helpers.font.CustomFont.<init>(CustomFont.java:41)
[23июн2023 00:57:40.120] [modloading-worker-1/INFO] [STDERR/]: [ru.saintby.SaintByClient.helpers.font.CustomFont:<init>:44]: 	at ru.saintby.SaintByClient.Wrapper.<clinit>(Wrapper.java:12)
[23июн2023 00:57:40.120] [modloading-worker-1/INFO] [STDERR/]: [ru.saintby.SaintByClient.helpers.font.CustomFont:<init>:44]: 	at ru.saintby.SaintByClient.ui.MainPane.<init>(MainPane.java:14)
[23июн2023 00:57:40.120] [modloading-worker-1/INFO] [STDERR/]: [ru.saintby.SaintByClient.helpers.font.CustomFont:<init>:44]: 	at ru.saintby.SaintByClient.ui.GuiScreen.<init>(GuiScreen.java:27)
[23июн2023 00:57:40.120] [modloading-worker-1/INFO] [STDERR/]: [ru.saintby.SaintByClient.helpers.font.CustomFont:<init>:44]: 	at ru.saintby.SaintByClient.Client.<init>(Client.java:37)
[23июн2023 00:57:40.121] [modloading-worker-1/INFO] [STDERR/]: [ru.saintby.SaintByClient.helpers.font.CustomFont:<init>:44]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[23июн2023 00:57:40.121] [modloading-worker-1/INFO] [STDERR/]: [ru.saintby.SaintByClient.helpers.font.CustomFont:<init>:44]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[23июн2023 00:57:40.121] [modloading-worker-1/INFO] [STDERR/]: [ru.saintby.SaintByClient.helpers.font.CustomFont:<init>:44]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[23июн2023 00:57:40.121] [modloading-worker-1/INFO] [STDERR/]: [ru.saintby.SaintByClient.helpers.font.CustomFont:<init>:44]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[23июн2023 00:57:40.122] [modloading-worker-1/INFO] [STDERR/]: [ru.saintby.SaintByClient.helpers.font.CustomFont:<init>:44]: 	at java.lang.Class.newInstance(Class.java:442)
[23июн2023 00:57:40.122] [modloading-worker-1/INFO] [STDERR/]: [ru.saintby.SaintByClient.helpers.font.CustomFont:<init>:44]: 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81)
[23июн2023 00:57:40.122] [modloading-worker-1/INFO] [STDERR/]: [ru.saintby.SaintByClient.helpers.font.CustomFont:<init>:44]: 	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120)
[23июн2023 00:57:40.122] [modloading-worker-1/INFO] [STDERR/]: [ru.saintby.SaintByClient.helpers.font.CustomFont:<init>:44]: 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
[23июн2023 00:57:40.122] [modloading-worker-1/INFO] [STDERR/]: [ru.saintby.SaintByClient.helpers.font.CustomFont:<init>:44]: 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632)
[23июн2023 00:57:40.122] [modloading-worker-1/INFO] [STDERR/]: [ru.saintby.SaintByClient.helpers.font.CustomFont:<init>:44]: 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[23июн2023 00:57:40.123] [modloading-worker-1/INFO] [STDERR/]: [ru.saintby.SaintByClient.helpers.font.CustomFont:<init>:44]: 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[23июн2023 00:57:40.123] [modloading-worker-1/INFO] [STDERR/]: [ru.saintby.SaintByClient.helpers.font.CustomFont:<init>:44]: 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[23июн2023 00:57:40.123] [modloading-worker-1/INFO] [STDERR/]: [ru.saintby.SaintByClient.helpers.font.CustomFont:<init>:44]: 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
[23июн2023 00:57:40.124] [modloading-worker-1/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: saintbyclient, class ru.saintby.SaintByClient.Client
java.lang.ExceptionInInitializerError: null
	at ru.saintby.SaintByClient.ui.MainPane.<init>(MainPane.java:14) ~[?:?]
	at ru.saintby.SaintByClient.ui.GuiScreen.<init>(GuiScreen.java:27) ~[?:?]
	at ru.saintby.SaintByClient.Client.<init>(Client.java:37) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_372]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_372]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_372]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_372]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_372]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[forge:36.2]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) [?:1.8.0_372]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632) [?:1.8.0_372]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_372]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_372]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_372]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) [?:1.8.0_372]
Caused by: java.lang.NullPointerException
	at ru.saintby.SaintByClient.helpers.font.CustomFont.<init>(CustomFont.java:50) ~[?:?]
	at ru.saintby.SaintByClient.Wrapper.<clinit>(Wrapper.java:12) ~[?:?]
	... 16 more
[23июн2023 00:57:40.328] [Render thread/FATAL] [net.minecraftforge.fml.ModLoader/LOADING]: Failed to complete lifecycle event CONSTRUCT, 2 errors found
[23июн2023 00:57:40.354] [Render thread/WARN] [net.minecraft.client.GameSettings/]: Removed resource pack mod_resources from options because it doesn't seem to exist anymore
[23июн2023 00:57:40.509] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.sound.SoundLoadEvent to a broken mod state
[23июн2023 00:57:40.702] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.ColorHandlerEvent$Block to a broken mod state
[23июн2023 00:57:40.705] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.ColorHandlerEvent$Item to a broken mod state
[23июн2023 00:57:40.929] [Render thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 17ec8328-3040-411c-b620-3ba053e55ae9
[23июн2023 00:57:40.980] [Render thread/INFO] [STDOUT/]: [net.minecraft.util.registry.Bootstrap:realStdoutPrintln:123]: ---- Minecraft Crash Report ----
// Oops.

Time: 23.06.23 0:57
Description: Initializing game

java.lang.NoClassDefFoundError: ru.saintby.SaintByClient.Wrapper
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:465) ~[forge-1.16.5-36.2.34_mapped_official_1.16.5-recomp.jar:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:topkahitboxes.mixin.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:149) ~[forge-1.16.5-36.2.34_mapped_official_1.16.5-recomp.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_372] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_372] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_372] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_372] {}
	at net.minecraftforge.userdev.FMLUserdevClientLaunchProvider.lambda$launchService$0(FMLUserdevClientLaunchProvider.java:52) ~[forge-1.16.5-36.2.34_mapped_official_1.16.5-recomp.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}
	at net.minecraftforge.userdev.LaunchTesting.main(LaunchTesting.java:108) [forge-1.16.5-36.2.34_mapped_official_1.16.5-recomp.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:465) ~[forge:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:topkahitboxes.mixin.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:149) ~[forge-1.16.5-36.2.34_mapped_official_1.16.5-recomp.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_372] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_372] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_372] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_372] {}
	at net.minecraftforge.userdev.FMLUserdevClientLaunchProvider.lambda$launchService$0(FMLUserdevClientLaunchProvider.java:52) ~[forge-1.16.5-36.2.34_mapped_official_1.16.5-recomp.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}
	at net.minecraftforge.userdev.LaunchTesting.main(LaunchTesting.java:108) [forge-1.16.5-36.2.34_mapped_official_1.16.5-recomp.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Mac OS X (x86_64) version 10.13.6
	Java Version: 1.8.0_372, Temurin
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Temurin
	Memory: 1034308800 bytes (986 MB) / 1722810368 bytes (1643 MB) up to 3817865216 bytes (3641 MB)
	CPUs: 4
	JVM Flags: 2 total; -XX:+IgnoreUnrecognizedVMOptions -Xss1M
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmluserdevclient
	ModLauncher naming: mcp
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.34_mapped_official_1.16.5-launcher.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.34_mapped_official_1.16.5-launcher.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.34_mapped_official_1.16.5-launcher.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.34_mapped_official_1.16.5-launcher.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.34_mapped_official_1.16.5-launcher.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.34
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		client-extra.jar                                  |Minecraft                     |minecraft                     |1.16.5              |CREATE_REG|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		main                                              |SaintByClient           |saintbyclient                 |2.0                 |ERROR     |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.34_mapped_official_1.16.5-recomp|Forge                         |forge                         |36.2.34             |CREATE_REG|Manifest: NOSIGNATURE
		TopkaHitboxes-2.0-1.16.5-forge.jar                |TopkaHitboxes           |topkahitboxes                 |2.0                 |ERROR     |Manifest: NOSIGNATURE
	Crash Report UUID: 17ec8328-3040-411c-b620-3ba053e55ae9
	Launched Version: MOD_DEV
	Backend library: LWJGL version 3.2.1 build 12
	Backend API: AMD Radeon HD 6750M OpenGL Engine GL version 2.1 ATI-1.68.25, ATI Technologies Inc.
	GL Caps: Using framebuffer using ARB_framebuffer_object extension
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	CPU: 4x Intel(R) Core(TM) i5-2400S CPU @ 2.50GHz
[23июн2023 00:57:40.998] [Render thread/INFO] [STDOUT/]: [net.minecraft.util.registry.Bootstrap:realStdoutPrintln:123]: #@!@# Game crashed! Crash report saved to: #@!@# /Volumes/Mac_SSD/SaintByClient/run/./crash-reports/crash-2023-06-23_00.57.40-client.txt
`
основная ошибка:
`java.lang.NoSuchFieldError: field_151161_ac`

версия: forge 1.16.5 само собой (запускал через intellij idea)

**Comment by sxmurxy2007** [comment]
По-моему ты там чего-то своего надобавлял. Ищи ошибку у себя.
<img width="574" alt="Снимок экрана 2023-07-05 125804" src="https://github.com/sxmurxy2007/TopkaHitboxes-1.16.5/assets/46312126/d2d94c57-4e6d-4ed6-8949-a45ea5dfc2c4">

**Comment by sxmurxy2007** [comment]
ты что вообще делаешь? ты зачем готовый мод под лаунчеры запускаешь в среде?
